# Generated by Django 4.1.1 on 2022-09-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
