# Generated by Django 4.1.1 on 2022-12-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0007_alter_todomodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='profile_pics'),
        ),
    ]
